### ISSUE TITLE
Cluster & Client Support

### ISSUE THREAD

**Issue by flickerfly** [brandur/redis-cell#21]
I've got this up and running for some basic tests. I'm pretty excited about what it brings to the table. Thank you! 

Are you aware of this being implemented in a redis cluster scenario and how it may have performed? Also how does a redis client like predis support this new call?

**Comment by brandur** [comment]
Thanks! And thanks for trying it.

> Are you aware of this being implemented in a redis cluster scenario and how it may have performed?

Unfortunately no! I'm pretty sure that it is being used by a couple shops now, but it's quite difficult to get a feel for how widespread that is. For safety, I would still consider this "not widely production-vetted".

> Also how does a redis client like predis support this new call?

It varies a lot client to client. Many clients have an "arbitrary command" call that allows you to just pass a string and a series of arguments.

I don't know much about Predis, but was just reading their documentation, and they've been kind enough to [include a section for how to define a new command](https://github.com/nrk/predis#adding-new-commands).

They also have a function that allows you to make an arbitrary call:

``` php
$response = $client->executeRaw(['SET', 'foo', 'bar']);
```

**Comment by flickerfly** [comment]
Thanks, we do intend to do a good bit of testing across this module before putting into production. We originally skipped over it because of that comment, but the more we evaluated our needs, this seemed like the right solution aside from that, one of the major factors being speed compared to implementing this in code with additional redis calls and the network latency on each call. Our situation puts us in need of likely checking at least 2 different thresholds so the informal benchmarks, and the implementation in RUST to focus on speed caught our eye.

Do you have any thoughts about what you want to see to consider this more production-vetted? Maybe we can share some of our work with it to assist.

Thanks for the Predis research. That looks pretty straight forward. Our initial testing, just throwing raw CL.THROTTLE calls from bash scripts, is looking good to fill out purposes.

**Comment by brandur** [comment]
Glad it helped!

> Do you have any thoughts about what you want to see to consider this more production-vetted? Maybe we can share some of our work with it to assist.

I think if I knew of just a few shops running this on fairly high volume services, and with reasonable success, that would be enough. I'd love to hear how your project turns out.

**Comment by flickerfly** [comment]
I'll keep you informed!

**Comment by brandur** [comment]
Very late follow up: I ended up removing the note about not being widely vetted after confirming in #24 that it's being used in production. Out of curiosity, did you end up doing anything with it?

Regardless, I'm doing a little issue cleanup and going to close this out for now.

**Comment by flickerfly** [comment]
We did. We decided not to use cluster capabilities though as that was not
working as expected. Very happy with the work. Thanks!
