### ISSUE TITLE
Decouple redismodule - rust integration from redis-cell

### ISSUE THREAD

**Issue by siscia** [brandur/redis-cell#5]
Hi @brandur,

I don't have much experience in rust however I am wondering how complex would be to decouple the part of the code base that interact with redis from your module.

Ideally I wonder how much work would be to create a crate to simply plug inside the dependencies.

Best,

Simone

**Comment by brandur** [comment]
Hi @siscia,

Yeah, actually I don't think it would be too bad to decouple a crate. I'd been meaning to do it over the holiday break, but didn't quite get around to it. I'll see if I can make some time in the next week or so.

Thanks for the reminder :)

**Comment by Eijebong** [comment]
Any news on that ? :)

**Comment by brandur** [comment]
Hah, sorry, I suck. No meaningful progress as of yet.

**Comment by dwerner** [comment]
I just submitted a PR that does this, but there I also change the API a bit. If you're interested in what it might look like - #10

**Comment by mrzahrada** [comment]
Hi, there is official [redismodule-rs](https://github.com/RedisLabsModules/redismodule-rs) crate now.
I've noticed this issue while browsing. I think it might be closed.

**Comment by brandur** [comment]
Ah very nice. Thank you @mrzahrada. Going to close this out.
