### ISSUE TITLE
Production readiness

### ISSUE THREAD

**Issue by tlvenn** [brandur/redis-cell#6]
I was wondering if this was used at Stripe in Production ?

I saw this [article](https://stripe.com/blog/rate-limiters) from Stripe blog on Rate Limiting mentioning the usage of Redis and was curious to see if there was any plan to leverage redis-cell ?

**Comment by brandur** [comment]
> I was wondering if this was used at Stripe in Production ?

I'm afraid to say that it's not! redis-cell is based on the relatively new module system, and we're using AWS ElastiCache for our Redis' in production, which as far as I know does not support it.

We are using [throttled](https://github.com/throttled/throttled) in some places for Go apps.

Most of the limiters described in the article are using home grown Ruby/Lua code though, and it's not public (currently the implementation would not make high quality OSS).

Thanks for your interest, and let me know if I can answer anything else.

**Comment by tlvenn** [comment]
Thanks for the feedback @brandur !
