### ISSUE TITLE
CL.THROTTLE implementation in Dragonfly

### ISSUE THREAD

**Issue by kakserpom** [brandur/redis-cell#61]
Hey! 

There's an open source project called Dragonfly (https://dragonflydb.io/), it is a multi-threaded Redis clone written from scratch.

CL.THROTTLE command has been recently implemented in Dragonfly keeping the same behavior and interface.
https://github.com/dragonflydb/dragonfly/pull/714

**Comment by brandur** [comment]
@kakserpom Very, very cool – thanks for the heads up! I'll tweet/blog this tomorrow.

**Comment by brandur** [comment]
Welp, took me way longer to get to this than I expected, but I did a mini-writeup here:

https://brandur.org/fragments/dragonflydb-cl-throttle

Thanks!
