### ISSUE TITLE
CI fixes welcome?

### ISSUE THREAD

**Issue by dbaynard** [brandur/redis-cell#63]
https://github.com/brandur/redis-cell/blob/bada85d5df0908a8372b4081845ef464a5702125/.github/workflows/ci.yml#L183-L189

I noticed this library still uses `::set-output`, [which is deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). The fix (4 lines) shouls be straightforward.

```diff
-echo ::set-output name=file_name::${REPOSITORY_NAME##*/}-${TAG_REF_NAME##*/}-${{ matrix.target }}.tar.gz # RepositoryName-v1.0.0-arch.tar.gz
+echo "name=file_name::${REPOSITORY_NAME##*/}-${TAG_REF_NAME##*/}-${{ matrix.target }}.tar.gz" >> "$GITHUB_OUTPUT" # RepositoryName-v1.0.0-arch.tar.gz
```

I see CI is also throwing rust errors. I don't mind taking a look, if I'm to update the CI anyway. Would a PR be welcome?

**Comment by brandur** [comment]
Hi @dbaynard, sorry about the really slow response on this one.

Yep, PRs welcome. I haven't taken a look at CI in a while, but I imagine it might need a bit of a modernization pass.

**Comment by dbaynard** [comment]
Ah I see you yourself fixed the breakages — it's just the warnings left, now.

I'll PR with the fixes (for deprecated `::set-output`, as above, and updates to actions to fix the node.js issue). I'll add [Keeping your actions up to date with Dependabot - GitHub Docs](https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot) too — on a monthly schedule.

**Comment by brandur** [comment]
Excellent, thank you. And yeah, I pushed a few fixes this afternoon that repaired the most egregious problems.

**Comment by brandur** [comment]
Going to close this in favor of #68 and related PRs.
